### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by ppires2000** [navilg/godaddy-ddns#22]
Hello.

Trying to run this container via portainer on a Rapsberrypi3 and, in the logs, I am getting: _exec /app/container-entrypoint.sh: exec format error_

I using the image: linuxshots/godaddy-ddns:arm64v8-linux-1.0.0.

Does this runs on a Raspberrypi3 or only Raspberrypi4?

Any ideas?

Thank you

**Comment by navilg** [comment]
`exec format error` usually occur when cpu architecture is not supported by binary.

This has not been tested on RPi3. Could you help me with below details:

- CPU details
- OS details

You can also build the image for your device using your device using below command and use it. This will make sure binary is built as per your device architecture.

```
git clone https://github.com/navilg/godaddy-ddns.git && cd godaddy-ddns.git
docker build --build-arg OS=OSNAME --build-arg ARCH=CPUARCH -t imagename:tag .
```

OSNAME is OS of your RPi e.g. linux
CPU arch can be arm64 or arm (for 32 bit)

Let me know if this works

**Comment by navilg** [comment]
Check new version
