### ISSUE TITLE
Can I use godaddy-ddns to update the IP of my main domain?

### ISSUE THREAD

**Issue by delaviux** [navilg/godaddy-ddns#31]
Hello, sorry for my bad English, it is not my first language.
Before I start I want to clarify that I am a complete newbie to networks and the Internet, so I may actually be asking a stupid question.
I am using your script to have a ddns with godaddy. It works very well, thanks for creating something so good.
But I have a question, could I use this script to update the IP of my main domain?
I mean, using the syntax that is in the instructions I can create a subdomain that obtains the IP address if it changes. But could godaddy-ddns be applied for the current main record?
I'm thinking something like:
`docker run --name @.example.com -d --restart unless-stopped --env GD_NAME=@ --env GD_DOMAIN=example.com --env GD_TTL=1200 --env GD_KEY=key-value-from-godaddy-developer-console --env GD_SECRET=secret-key-value-from-godaddy-developer-console linuxshots/godaddy-ddns:latest`
According to godaddy the "@" is used to add an A record in the main domain. I was wondering if I could apply the same in godaddy-ddns.

**Comment by navilg** [comment]
Yes. You can use command something like below:

```
docker run --name example.com -d --restart unless-stopped --env GD_NAME=@ --env GD_DOMAIN=example.com --env GD_TTL=1200 --env GD_KEY=key-value-from-godaddy-developer-console --env GD_SECRET=secret-key-value-from-godaddy-developer-console linuxshots/godaddy-ddns:latest
```

**Comment by delaviux** [comment]
Thank you sir. It works impeccably. You can consider this topic closed.
